In [1]:
import numpy as np
print(np.version)
print(np.show_config())

<module 'numpy.version' from 'C:\\Users\\chanti\\Music\\chanti\\lib\\site-packages\\numpy\\version.py'>
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/chanti/Music/chanti\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/chanti/Music/chanti\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/chanti/Music/chanti\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/chanti/Music/chanti\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/chanti/Music/chanti\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/chanti/Music/chanti\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/chanti/Music/chanti\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_C

In [3]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [8]:
a1=np.array([1,2,3,])
print(a1.all())
a2=np.array([0,3,4,0,0,np.nan,np.inf])
print(a2.all())

True
False


In [8]:
print(a1.any())
print(a2.any())

True
True


In [9]:
a3=np.array([0,0,0])
print(a3.all())
print(a3.any())

False
False


In [32]:
#test element wise for +ve or -ve
print(np.isposinf(a1))
print(np.isneginf(a1))
print(np.isinf(a1))


[False False False]
[False False False]
[False False False]


In [12]:
#isinfinite
print(np.isfinite(a1))

[ True  True  True]


In [20]:
ar=np.array([1,2,0,np.nan,np.inf])
print(np.isfinite(ar))

[ True  True  True False False]


In [29]:
ar1=np.array([23.45,12.345])
print(np.isfinite(ar1))

[ True  True]


In [41]:
ar2=([np.nan,np.inf,565,-67])
print(np.isneginf(ar2))

[False False False False]


In [5]:
import numpy as np
ar2=([np.nan,np.inf,565,-67])
print(np.isnan(ar2))

[ True False False False]


In [15]:
import numpy as np
a=np.array([1,2,3,3.4,56,np.nan,np.inf,1+1j])
print(np.isscalar(a))
print(np.isreal(a))
print(np.iscomplex(a))

False
[ True  True  True  True  True  True  True False]
[False False False False False False False  True]


In [16]:
print(np.isscalar(1))

True


In [1]:
import numpy as np
x=np.array([2,3,4])
y=np.array([89,0,3])
print(x)
print(y)
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(y,x))

[2 3 4]
[89  0  3]
[False  True  True]
[False  True  True]
[ True False False]
[False  True  True]


In [6]:
X = np.array([1, 7, 13, 105])
print("Original array:")
print(X)
print("Size of  the array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[  1   7  13 105]
Size of  the array:
16 bytes


In [7]:
print(np.ones(10))
print(np.zeros(10))
print(np.ones(10)*5)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [9]:
print(np.arange(30,71))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [10]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
print(np.random.normal(0,1,2))#(lower,upper,count)

[-1.35814094 -0.33199261]


In [14]:
print(np.random.normal(0,1,15))

[-1.61173723  1.31519878 -0.3669763  -0.10489682 -1.14464691  1.0240619
  1.49816855 -0.03737873 -0.56926866 -0.03518554 -0.19441369 -1.71470099
 -0.14795629 -0.58355046  1.35402181]


In [19]:
v= np.arange(15,55)
print(v)
print(v[1:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [3]:
import numpy as np
print(np.linspace(10,49,5))

[10.   19.75 29.5  39.25 49.  ]


In [8]:
v=(np.arange(21))
print(v)
v[(v >= 9) & (v <= 15)] *= -1
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [9]:
print(np.arange(0,11,5))

[ 0  5 10]


In [12]:
x=np.array([3,5,6])
y=np.array([65,7,8])
print(x*y)

[195  35  48]


In [20]:
print(np.arange(10,22).reshape(3,4))


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [21]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
print(np.eye(7))

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [2]:
import numpy as np
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [10]:
import numpy as np
x=np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [15]:
print(np.random.random((3,3,3)))

[[[0.75112816 0.96751768 0.81340179]
  [0.96024707 0.44675117 0.03264376]
  [0.07734558 0.38666792 0.31691483]]

 [[0.99453206 0.38822402 0.34663063]
  [0.61096805 0.76446353 0.10745416]
  [0.69495192 0.8215447  0.50031709]]

 [[0.64542809 0.81365228 0.03867082]
  [0.0784825  0.05466114 0.24929876]
  [0.71963385 0.20389813 0.04704217]]]


In [16]:
x=np.array([2,3])
y=np.array([9,7])
print(x)
print(y)
print(np.dot(x,y))

[2 3]
[9 7]
39


In [8]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.array([[1,2],[4,8]])
print(a)
print(b)
print(np.sum(a))
print(np.sum(b))
#print(np.sum(a, axis=0))
#print(np.sum(a, axis=1))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))


[1 2 3]
[4 5 6]
6
15
[ 5 10]
[ 3 12]


In [15]:
import numpy as np
a = [[1, 2], [3, 4]]
x = np.array(a)
print(a)
print(x)
a2 = x.tolist()
print(a == a2)


[[1, 2], [3, 4]]
[[1 2]
 [3 4]]
True


In [17]:
import numpy as np
x = np.float32(0)
print(x)
print(type(x))
pyval = x.item()
print(type(pyval))

0.0
<class 'numpy.float32'>
<class 'float'>


In [22]:
x=np.array([2,3,4])
y=np.array([5,6,7])
z=np.array([2,6,4])
print(x)
print(y)
print(np.equal(x,y,))

[2 3 4]
[5 6 7]
[False False False]


In [32]:
x=np.array([[2,3,4],[32,6,0],[22,4,5]])
print(np.sort(x))
print(np.sort(x,axis=0))#column wise
print(np.sort(x,axis=1))#row wise

[[ 2  3  4]
 [ 0  6 32]
 [ 4  5 22]]
[[ 2  3  0]
 [22  4  4]
 [32  6  5]]
[[ 2  3  4]
 [ 0  6 32]
 [ 4  5 22]]


In [33]:
print(x[x<n])
n=3




NameError: name 'n' is not defined