In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [3]:
a.shape

(6,)

In [4]:
a.size

6

a.ndim

In [5]:
a.ndim

1

In [6]:
a=np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
print(a[1,4])

9


In [8]:
a=np.array([1,2,3,4])
print(a)
b=np.array([6,7,8,9])
print(b)
c=a+b
print(c)

[1 2 3 4]
[6 7 8 9]
[ 7  9 11 13]


In [9]:
print(type(a))
print(type(b))
print(type(c))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
print(a**3)

[ 1  8 27 64]


In [11]:
a.resize(2,2)
b.resize(2,2)
print(a)
print(b)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]


In [12]:
a*b

array([[ 6, 14],
       [24, 36]])

In [13]:
sum(a,b)

array([[10, 13],
       [12, 15]])

In [14]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]


In [15]:
print(a)

[[1 2]
 [3 4]]


In [16]:
np.sum(a,axis=0)

array([4, 6])

In [17]:
np.sum(a,axis=1)

array([3, 7])

In [18]:
c=np.array([1,2,3,4])
np.sum(c)

10

In [19]:
np.mean(c)

2.5

In [20]:
b=np.array([4,3,2,1])
print(b)

[4 3 2 1]


In [22]:
d=np.concatenate((b,c),axis=0)
d

array([4, 3, 2, 1, 1, 2, 3, 4])

In [23]:
print(b)
print(c)

[4 3 2 1]
[1 2 3 4]


In [24]:
print(np.unique(d))

[1 2 3 4]


In [25]:
print(d)

[4 3 2 1 1 2 3 4]


In [26]:
b[1]+c[2]

6

In [28]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [29]:
a1.max()

3

In [30]:
type(a1)

numpy.ndarray

In [36]:
print(a1.ndim)


1


In [38]:
a1=np.ones(2)
a1

array([1., 1.])

In [39]:
a2=np.zeros(2)
a2

array([0., 0.])

In [40]:
a3=np.empty(5)
a3

array([2.12199579e-314, 6.36598737e-314, 1.06099790e-313, 1.48539705e-313,
       1.90979621e-313])

In [42]:
a4=np.arange(10)
a4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a5=np.arange(1,10,2)
a5

array([1, 3, 5, 7, 9])

In [47]:
a6=np.linspace(0,10,5)
a6

array([ 0. ,  2.5,  5. ,  7.5, 10. ])