Ridge regression is a method we can use to fit a regression model when multicollinearity is present in the data.

In [4]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.linear_model import LinearRegression

In [5]:
x=np.array([891,23,5,4,6,786,678,322,4546,6765]).reshape(-1,1)
y=np.array([2324,45553,66,2,332,6534,654,643,76754,21334])
print(x)
print(y)

[[ 891]
 [  23]
 [   5]
 [   4]
 [   6]
 [ 786]
 [ 678]
 [ 322]
 [4546]
 [6765]]
[ 2324 45553    66     2   332  6534   654   643 76754 21334]


In [8]:
#model=LinearRegression()
#model.fit(x,y)

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=2)
x_train,x_test,y_train,y_test

(array([[   4],
        [ 891],
        [ 786],
        [ 322],
        [4546],
        [   5],
        [   6],
        [  23]]),
 array([[6765],
        [ 678]]),
 array([    2,  2324,  6534,   643, 76754,    66,   332, 45553]),
 array([21334,   654]))

In [9]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [11]:
y_p=model.predict(x_test)
y_p

array([104637.13117318,  14377.7617639 ])

ValueError: Expected 2D array, got 1D array instead:
array=[21334   654].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(x,y)


plt.show()

In [ ]:
import seaborn as sns
plt.scatter(x,y_p,color="deeppink",marker="*",alpha=0.9)